# Generated by Django 5.0.1 on 2024-02-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_paid_by_alter_payment_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_to',
            field=models.IntegerField(),
        ),
    ]
