# Generated by Django 5.0.1 on 2024-02-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_paid_by_alter_payment_paid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_by_names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
