# Generated by Django 5.0.1 on 2024-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_paid_to_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paidby_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paidto_id',
            field=models.IntegerField(null=True),
        ),
    ]
